## Linear regressions: relative [protein] vs. mean temperature in the last year (oC)

# Summary stats for linear models
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source('scripts/transformations.R')
require(ggplot2)
require(vegan)
library(readr)
library(knitr)
require(plyr)
require(reshape2)
require(dplyr)

tab <- regression_output(na.omit(protein_climate_D14_stand), tavg, sum)
kable(tab, "markdown", align="l", padding=10)
write_csv(tab, 'output/modelorder.csv')

modelorder <- read_csv('output/modelorder.csv')
````

# Linear regressions

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

modelorder <- modelorder[!modelorder$submodel %in% 'total_protein',]
blah <- na.omit(merge(protein_stand_D14_age, climate_locs, all=TRUE))

for(i in modelorder$submodel) {
  
prot <- blah[,c(3:29)][[i]]
protname <- names(blah[,c(3:29)][i])

g <- ggplot(blah, aes(x = tavg, y = prot)) + geom_point() 
g <- g + geom_smooth(method = 'lm', se=FALSE) + ylab(protname) + ggtitle(paste0(protname))
g <- g  + theme_bw()
g <- g + theme(panel.grid.major = element_blank(),
               panel.grid.minor = element_blank(), 
               legend.title=element_blank(),
               legend.position="bottom",
               axis.line = element_line(colour = "black"))

print(g)
}

````
