## Linear regressions: relative [protein] vs. irradiance at leaf (scaled by gap fraction)

# Summary stats for linear models
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
source('scripts/transformations.R')
require(ggplot2)
require(vegan)
library(readr)
library(knitr)
require(plyr)
require(reshape2)
require(dplyr)
require(lazyeval)

replicates <- read_csv('output/replicates.csv')
replicates <- replicates[replicates$sample %in% protein_stand_D14_age$sample,]

replicates <- merge(replicates, read_csv('data/lineage.csv'))

climate_locs$biological_rep <- NULL

data <- merge(protein_stand_D14_age, climate_locs)
#data$ID <- NULL
data <- merge(data, replicates, by = c('sample', 'Latitude', 'Longitude', 'leaf_age', 'site_revised', 'species_confirmed', 'date'))
data <- data[!duplicated(data$sample),]

data <- filter(data, ID != 'melpal_106')

data <- na.omit(data)

tab <- regression_agg(data, 'leafrad_mean', logx=FALSE)

kable(tab, "markdown", align="l", padding=10)
write_csv(tab, 'output/modelorder.csv')

modelorder <- read_csv('output/modelorder.csv')
````

# Linear regressions

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

for(i in modelorder$submodel) {
  
  agg_plot_leafrad(data, depvar = i, indepvar = 'leafrad_mean', logx=FALSE, labs = 'irradiance at leaf')
  
}

````
